# Country Selection

## Purpose
The purpose of this notebook is to map out the parameters for which I will use as a guideline to select the countries for this analysis.

The World Bank income classifications are used to establish the initial candidate pool. Selected countries will be evauluated based on geographic diversity
and the ITU data availability before the final sample is selected.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
## Download World Bank Dataset

df = pd.read_csv("../data/raw/nations_incomes_2026_07_15.csv")

In [ ]:
## Reviewing the head of the dataframe
df.head()

,Economy,Code,Region,Income group,Lending category
0,Afghanistan,AFG,"Middle East, North Africa, Afghanistan & Pakistan",Low income,IDA
1,Albania,ALB,Europe & Central Asia,Upper middle income,IBRD
2,Algeria,DZA,"Middle East, North Africa, Afghanistan & Pakistan",Upper middle income,IBRD
3,American Samoa,ASM,East Asia & Pacific,High income,NaN
4,Andorra,AND,Europe & Central Asia,High income,NaN

In [8]:
df.shape

(268, 5)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 268 entries, 0 to 267
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Economy           265 non-null    object
 1   Code              265 non-null    object
 2   Region            218 non-null    object
 3   Income group      218 non-null    object
 4   Lending category  145 non-null    object
dtypes: object(5)
memory usage: 10.6+ KB

In [10]:
df["Income group"].value_counts()

Income group
High income            87
Upper middle income    59
Lower middle income    47
Low income             25
Name: count, dtype: int64

In [11]:
df["Income group"].value_counts(dropna=False)

Income group
High income            87
Upper middle income    59
NaN                    50
Lower middle income    47
Low income             25
Name: count, dtype: int64

In [12]:
df[df["Income group"].isna()]

,Economy,Code,Region,Income group,Lending category
218,NaN,NaN,NaN,NaN,NaN
219,Africa Eastern and Southern,AFE,NaN,NaN,NaN
220,Africa Western and Central,AFW,NaN,NaN,NaN
221,Arab World,ARB,NaN,NaN,NaN
222,Caribbean small states,CSS,NaN,NaN,NaN
223,Central Europe and the Baltics,CEB,NaN,NaN,NaN
224,Early-demographic dividend,EAR,NaN,NaN,NaN
225,East Asia & Pacific,EAS,NaN,NaN,NaN
226,East Asia & Pacific (excluding high income),EAP,NaN,NaN,NaN
227,East Asia & Pacific (IDA & IBRD),TEA,NaN,NaN,NaN
228,Euro area,EMU,NaN,NaN,NaN
229,Europe & Central Asia,ECS,NaN,NaN,NaN
230,Europe & Central Asia (excluding high income),ECA,NaN,NaN,NaN
231,Europe & Central Asia (IDA & IBRD),TEC,NaN,NaN,NaN
232,European Union,EUU,NaN,NaN,NaN
233,Heavily indebted poor countries (HIPC),HPC,NaN,NaN,NaN
234,High income,HIC,NaN,NaN,NaN
235,IBRD only,IBD,NaN,NaN,NaN
236,IDA & IBRD total,IBT,NaN,NaN,NaN
237,IDA blend,IDB,NaN,NaN,NaN
238,IDA only,IDX,NaN,NaN,NaN
239,IDA total,IDA,NaN,NaN,NaN
240,Late-demographic dividend,LTE,NaN,NaN,NaN
241,Latin America & Caribbean,LCN,NaN,NaN,NaN
242,Latin America & Caribbean (excluding high income),LAC,NaN,NaN,NaN
243,Latin America & Caribbean (IDA & IBRD),TLA,NaN,NaN,NaN
244,Least developed countries: UN classification,LDC,NaN,NaN,NaN
245,Low & middle income,LMY,NaN,NaN,NaN
246,Low income,LIC,NaN,NaN,NaN
247,Lower middle income,LMC,NaN,NaN,NaN
248,"Middle East, North Africa, Afghanistan and Pak...",MEA,NaN,NaN,NaN
249,"Middle East, North Africa, Afghanistan and Pak...",MNA,NaN,NaN,NaN
250,"Middle East, North Africa, Afghanistan and Pak...",TMN,NaN,NaN,NaN
251,Middle income,MIC,NaN,NaN,NaN
252,North America,NAC,NaN,NaN,NaN
253,OECD members,OED,NaN,NaN,NaN
254,Other small states,OSS,NaN,NaN,NaN
255,Pacific island small states,PSS,NaN,NaN,NaN
256,Post-demographic dividend,PST,NaN,NaN,NaN
257,Pre-demographic dividend,PRE,NaN,NaN,NaN
258,Small states,SST,NaN,NaN,NaN
259,South Asia,SAS,NaN,NaN,NaN
260,South Asia (IDA & IBRD),TSA,NaN,NaN,NaN
261,Sub-Saharan Africa,SSF,NaN,NaN,NaN
262,Sub-Saharan Africa (excluding high income),SSA,NaN,NaN,NaN
263,Sub-Saharan Africa (IDA & IBRD),TSS,NaN,NaN,NaN
264,Upper middle income,UMC,NaN,NaN,NaN
265,World,WLD,NaN,NaN,NaN
266,NaN,NaN,NaN,NaN,NaN
267,NaN,NaN,NaN,NaN,NaN

In [13]:
# Creating New dataframe to filter econimies

## This dataset contains both individual economies and aggregated groups such as regions, income gaps etc. The aggregated records contain the income classification
## that is needed to conduct this analysis and there are not included. All records with a non-null have been retained to creat the candidate economy dataset.

In [14]:
countries = df[df["Income group"].notna()].copy()

In [15]:
countries.shape

(218, 5)

In [17]:
countries.isna().sum()

Economy              0
Code                 0
Region               0
Income group         0
Lending category    73
dtype: int64

In [19]:
countries["Region"].value_counts()

Region
Europe & Central Asia                                58
Sub-Saharan Africa                                   48
Latin America & Caribbean                            42
East Asia & Pacific                                  38
Middle East, North Africa, Afghanistan & Pakistan    23
South Asia                                            6
North America                                         3
Name: count, dtype: int64

In [27]:
SSA = countries[countries["Region"] == "Sub-Saharan Africa"]

In [28]:
SSA.shape

(48, 5)

In [30]:
SSA.info()

<class 'pandas.core.frame.DataFrame'>
Index: 48 entries, 5 to 217
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Economy           48 non-null     object
 1   Code              48 non-null     object
 2   Region            48 non-null     object
 3   Income group      48 non-null     object
 4   Lending category  48 non-null     object
dtypes: object(5)
memory usage: 2.2+ KB

In [31]:
SSA_list = SSA["Economy"].tolist()

In [34]:
SSA_list

['Angola',
 'Benin',
 'Botswana',
 'Burkina Faso',
 'Burundi',
 'Cabo Verde',
 'Cameroon',
 'Central African Republic',
 'Chad',
 'Comoros',
 'Congo, Dem. Rep.',
 'Congo, Rep.',
 'Côte d’Ivoire',
 'Equatorial Guinea',
 'Eritrea',
 'Eswatini',
 'Ethiopia',
 'Gabon',
 'Gambia, The',
 'Ghana',
 'Guinea',
 'Guinea-Bissau',
 'Kenya',
 'Lesotho',
 'Liberia',
 'Madagascar',
 'Malawi',
 'Mali',
 'Mauritania',
 'Mauritius',
 'Mozambique',
 'Namibia',
 'Niger',
 'Nigeria',
 'Rwanda',
 'São Tomé and Príncipe',
 'Senegal',
 'Seychelles',
 'Sierra Leone',
 'Somalia, Fed. Rep.',
 'South Africa',
 'South Sudan',
 'Sudan',
 'Tanzania',
 'Togo',
 'Uganda',
 'Zambia',
 'Zimbabwe']

In [38]:
countries["Income group"].value_counts()

Income group
High income            87
Upper middle income    59
Lower middle income    47
Low income             25
Name: count, dtype: int64

In [39]:
high_income = countries[countries["Income group"] == "High income"]

high_income

,Economy,Code,Region,Income group,Lending category
3,American Samoa,ASM,East Asia & Pacific,High income,NaN
4,Andorra,AND,Europe & Central Asia,High income,NaN
6,Antigua and Barbuda,ATG,Latin America & Caribbean,High income,IBRD
9,Aruba,ABW,Latin America & Caribbean,High income,NaN
10,Australia,AUS,East Asia & Pacific,High income,NaN
...,...,...,...,...,...
205,United Arab Emirates,ARE,"Middle East, North Africa, Afghanistan & Pakistan",High income,NaN
206,United Kingdom,GBR,Europe & Central Asia,High income,NaN
207,United States,USA,North America,High income,NaN
208,Uruguay,URY,Latin America & Caribbean,High income,IBRD
213,Virgin Islands (U.S.),VIR,Latin America & Caribbean,High income,NaN

In [42]:
upper_middle_income = countries[countries["Income group"] == "Upper middle income"]

upper_middle_income

,Economy,Code,Region,Income group,Lending category
1,Albania,ALB,Europe & Central Asia,Upper middle income,IBRD
2,Algeria,DZA,"Middle East, North Africa, Afghanistan & Pakistan",Upper middle income,IBRD
7,Argentina,ARG,Latin America & Caribbean,Upper middle income,IBRD
8,Armenia,ARM,Europe & Central Asia,Upper middle income,IBRD
12,Azerbaijan,AZE,Europe & Central Asia,Upper middle income,IBRD
17,Belarus,BLR,Europe & Central Asia,Upper middle income,IBRD
19,Belize,BLZ,Latin America & Caribbean,Upper middle income,Blend
24,Bosnia and Herzegovina,BIH,Europe & Central Asia,Upper middle income,IBRD
25,Botswana,BWA,Sub-Saharan Africa,Upper middle income,IBRD
26,Brazil,BRA,Latin America & Caribbean,Upper middle income,IBRD
32,Cabo Verde,CPV,Sub-Saharan Africa,Upper middle income,Blend
41,China,CHN,East Asia & Pacific,Upper middle income,IBRD
42,Colombia,COL,Latin America & Caribbean,Upper middle income,IBRD
49,Cuba,CUB,Latin America & Caribbean,Upper middle income,NaN
55,Dominica,DMA,Latin America & Caribbean,Upper middle income,Blend
56,Dominican Republic,DOM,Latin America & Caribbean,Upper middle income,IBRD
57,Ecuador,ECU,Latin America & Caribbean,Upper middle income,IBRD
59,El Salvador,SLV,Latin America & Caribbean,Upper middle income,IBRD
60,Equatorial Guinea,GNQ,Sub-Saharan Africa,Upper middle income,IBRD
66,Fiji,FJI,East Asia & Pacific,Upper middle income,Blend
70,Gabon,GAB,Sub-Saharan Africa,Upper middle income,IBRD
72,Georgia,GEO,Europe & Central Asia,Upper middle income,IBRD
78,Grenada,GRD,Latin America & Caribbean,Upper middle income,Blend
80,Guatemala,GTM,Latin America & Caribbean,Upper middle income,IBRD
90,Indonesia,IDN,East Asia & Pacific,Upper middle income,IBRD
91,"Iran, Islamic Rep.",IRN,"Middle East, North Africa, Afghanistan & Pakistan",Upper middle income,IBRD
92,Iraq,IRQ,"Middle East, North Africa, Afghanistan & Pakistan",Upper middle income,IBRD
97,Jamaica,JAM,Latin America & Caribbean,Upper middle income,IBRD
99,Jordan,JOR,"Middle East, North Africa, Afghanistan & Pakistan",Upper middle income,IBRD
100,Kazakhstan,KAZ,Europe & Central Asia,Upper middle income,IBRD
105,Kosovo,XKX,Europe & Central Asia,Upper middle income,IDA
113,Libya,LBY,"Middle East, North Africa, Afghanistan & Pakistan",Upper middle income,IBRD
120,Malaysia,MYS,East Asia & Pacific,Upper middle income,IBRD
121,Maldives,MDV,South Asia,Upper middle income,IDA
124,Marshall Islands,MHL,East Asia & Pacific,Upper middle income,IDA
126,Mauritius,MUS,Sub-Saharan Africa,Upper middle income,IBRD
127,Mexico,MEX,Latin America & Caribbean,Upper middle income,IBRD
128,"Micronesia, Fed. Sts.",FSM,East Asia & Pacific,Upper middle income,IDA
129,Moldova,MDA,Europe & Central Asia,Upper middle income,IBRD
131,Mongolia,MNG,East Asia & Pacific,Upper middle income,IBRD
132,Montenegro,MNE,Europe & Central Asia,Upper middle income,IBRD
145,North Macedonia,MKD,Europe & Central Asia,Upper middle income,IBRD
153,Paraguay,PRY,Latin America & Caribbean,Upper middle income,IBRD
154,Peru,PER,Latin America & Caribbean,Upper middle income,IBRD
155,Philippines,PHL,East Asia & Pacific,Upper middle income,IBRD
163,Samoa,WSM,East Asia & Pacific,Upper middle income,IDA
168,Serbia,SRB,Europe & Central Asia,Upper middle income,IBRD
177,South Africa,ZAF,Sub-Saharan Africa,Upper middle income,IBRD
180,Sri Lanka,LKA,South Asia,Upper middle income,IDA
182,St. Lucia,LCA,Latin America & Caribbean,Upper middle income,Blend
184,St. Vincent and the Grenadines,VCT,Latin America & Caribbean,Upper middle income,Blend
186,Suriname,SUR,Latin America & Caribbean,Upper middle income,Blend
193,Thailand,THA,East Asia & Pacific,Upper middle income,IBRD
196,Tonga,TON,East Asia & Pacific,Upper middle income,IDA
199,Türkiye,TUR,Europe & Central Asia,Upper middle income,IBRD
200,Turkmenistan,TKM,Europe & Central Asia,Upper middle income,IBRD
202,Tuvalu,TUV,East Asia & Pacific,Upper middle income,IDA
204,Ukraine,UKR,Europe & Central Asia,Upper middle income,IBRD
212,Viet Nam,VNM,East Asia & Pacific,Upper middle income,IBRD

In [43]:
lower_middle_income = countries[countries["Income group"] == "Lower middle income"]

lower_middle_income

,Economy,Code,Region,Income group,Lending category
5,Angola,AGO,Sub-Saharan Africa,Lower middle income,IBRD
15,Bangladesh,BGD,South Asia,Lower middle income,IDA
20,Benin,BEN,Sub-Saharan Africa,Lower middle income,IDA
22,Bhutan,BTN,South Asia,Lower middle income,IDA
23,Bolivia,BOL,Latin America & Caribbean,Lower middle income,IBRD
33,Cambodia,KHM,East Asia & Pacific,Lower middle income,IDA
34,Cameroon,CMR,Sub-Saharan Africa,Lower middle income,Blend
43,Comoros,COM,Sub-Saharan Africa,Lower middle income,IDA
45,"Congo, Rep.",COG,Sub-Saharan Africa,Lower middle income,Blend
47,Côte d’Ivoire,CIV,Sub-Saharan Africa,Lower middle income,Blend
54,Djibouti,DJI,"Middle East, North Africa, Afghanistan & Pakistan",Lower middle income,IDA
58,"Egypt, Arab Rep.",EGY,"Middle East, North Africa, Afghanistan & Pakistan",Lower middle income,IBRD
63,Eswatini,SWZ,Sub-Saharan Africa,Lower middle income,Blend
74,Ghana,GHA,Sub-Saharan Africa,Lower middle income,IDA
81,Guinea,GIN,Sub-Saharan Africa,Lower middle income,IDA
84,Haiti,HTI,Latin America & Caribbean,Lower middle income,IDA
85,Honduras,HND,Latin America & Caribbean,Lower middle income,IDA
89,India,IND,South Asia,Lower middle income,IBRD
101,Kenya,KEN,Sub-Saharan Africa,Lower middle income,Blend
102,Kiribati,KIR,East Asia & Pacific,Lower middle income,IDA
107,Kyrgyz Republic,KGZ,Europe & Central Asia,Lower middle income,IDA
108,Lao PDR,LAO,East Asia & Pacific,Lower middle income,IDA
110,Lebanon,LBN,"Middle East, North Africa, Afghanistan & Pakistan",Lower middle income,IBRD
111,Lesotho,LSO,Sub-Saharan Africa,Lower middle income,IDA
125,Mauritania,MRT,Sub-Saharan Africa,Lower middle income,IDA
133,Morocco,MAR,"Middle East, North Africa, Afghanistan & Pakistan",Lower middle income,IBRD
135,Myanmar,MMR,East Asia & Pacific,Lower middle income,IDA
136,Namibia,NAM,Sub-Saharan Africa,Lower middle income,IBRD
138,Nepal,NPL,South Asia,Lower middle income,IDA
142,Nicaragua,NIC,Latin America & Caribbean,Lower middle income,IDA
144,Nigeria,NGA,Sub-Saharan Africa,Lower middle income,Blend
149,Pakistan,PAK,"Middle East, North Africa, Afghanistan & Pakistan",Lower middle income,Blend
152,Papua New Guinea,PNG,East Asia & Pacific,Lower middle income,Blend
165,São Tomé and Príncipe,STP,Sub-Saharan Africa,Lower middle income,IDA
167,Senegal,SEN,Sub-Saharan Africa,Lower middle income,IDA
175,Solomon Islands,SLB,East Asia & Pacific,Lower middle income,IDA
191,Tajikistan,TJK,Europe & Central Asia,Lower middle income,IDA
192,Tanzania,TZA,Sub-Saharan Africa,Lower middle income,IDA
194,Timor-Leste,TLS,East Asia & Pacific,Lower middle income,Blend
195,Togo,TGO,Sub-Saharan Africa,Lower middle income,IDA
198,Tunisia,TUN,"Middle East, North Africa, Afghanistan & Pakistan",Lower middle income,IBRD
209,Uzbekistan,UZB,Europe & Central Asia,Lower middle income,Blend
210,Vanuatu,VUT,East Asia & Pacific,Lower middle income,IDA
211,"Venezuela, RB",VEN,Latin America & Caribbean,Lower middle income,IBRD
214,West Bank and Gaza,PSE,"Middle East, North Africa, Afghanistan & Pakistan",Lower middle income,NaN
216,Zambia,ZMB,Sub-Saharan Africa,Lower middle income,IDA
217,Zimbabwe,ZWE,Sub-Saharan Africa,Lower middle income,Blend

In [46]:
lower_income = countries[countries["Income group"] == "Low income"]

lower_income

,Economy,Code,Region,Income group,Lending category
0,Afghanistan,AFG,"Middle East, North Africa, Afghanistan & Pakistan",Low income,IDA
30,Burkina Faso,BFA,Sub-Saharan Africa,Low income,IDA
31,Burundi,BDI,Sub-Saharan Africa,Low income,IDA
37,Central African Republic,CAF,Sub-Saharan Africa,Low income,IDA
38,Chad,TCD,Sub-Saharan Africa,Low income,IDA
44,"Congo, Dem. Rep.",COD,Sub-Saharan Africa,Low income,IDA
61,Eritrea,ERI,Sub-Saharan Africa,Low income,IDA
64,Ethiopia,ETH,Sub-Saharan Africa,Low income,IDA
71,"Gambia, The",GMB,Sub-Saharan Africa,Low income,IDA
82,Guinea-Bissau,GNB,Sub-Saharan Africa,Low income,IDA
103,"Korea, Dem. People's Rep.",PRK,East Asia & Pacific,Low income,NaN
112,Liberia,LBR,Sub-Saharan Africa,Low income,IDA
118,Madagascar,MDG,Sub-Saharan Africa,Low income,IDA
119,Malawi,MWI,Sub-Saharan Africa,Low income,IDA
122,Mali,MLI,Sub-Saharan Africa,Low income,IDA
134,Mozambique,MOZ,Sub-Saharan Africa,Low income,IDA
143,Niger,NER,Sub-Saharan Africa,Low income,IDA
162,Rwanda,RWA,Sub-Saharan Africa,Low income,IDA
170,Sierra Leone,SLE,Sub-Saharan Africa,Low income,IDA
176,"Somalia, Fed. Rep.",SOM,Sub-Saharan Africa,Low income,IDA
178,South Sudan,SSD,Sub-Saharan Africa,Low income,IDA
185,Sudan,SDN,Sub-Saharan Africa,Low income,IDA
189,Syrian Arab Republic,SYR,"Middle East, North Africa, Afghanistan & Pakistan",Low income,IDA
203,Uganda,UGA,Sub-Saharan Africa,Low income,IDA
215,"Yemen, Rep.",YEM,"Middle East, North Africa, Afghanistan & Pakistan",Low income,IDA

In [ ]:
## Converted the separate income lists into their own groups. How I will filter on the countries from that income group & what region they are in 

countries["Region"].unique()

array(['Middle East, North Africa, Afghanistan & Pakistan',
       'Europe & Central Asia', 'East Asia & Pacific',
       'Sub-Saharan Africa', 'Latin America & Caribbean', 'South Asia',
       'North America'], dtype=object)

In [50]:
upper_middle_income_SSA = countries[(countries["Region"] == "Sub-Saharan Africa") & (countries["Income group"] == "Upper middle income")]

upper_middle_income_SSA

,Economy,Code,Region,Income group,Lending category
25,Botswana,BWA,Sub-Saharan Africa,Upper middle income,IBRD
32,Cabo Verde,CPV,Sub-Saharan Africa,Upper middle income,Blend
60,Equatorial Guinea,GNQ,Sub-Saharan Africa,Upper middle income,IBRD
70,Gabon,GAB,Sub-Saharan Africa,Upper middle income,IBRD
126,Mauritius,MUS,Sub-Saharan Africa,Upper middle income,IBRD
177,South Africa,ZAF,Sub-Saharan Africa,Upper middle income,IBRD

In [51]:
region_income = pd.crosstab( countries["Region"], countries["Income group"])

region_income

Income group,High income,Low income,Lower middle income,Upper middle income
Region,,,,
East Asia & Pacific,16,1,8,13
Europe & Central Asia,40,0,3,15
Latin America & Caribbean,19,0,5,18
"Middle East, North Africa, Afghanistan & Pakistan",8,3,7,5
North America,3,0,0,0
South Asia,0,0,4,2
Sub-Saharan Africa,1,21,20,6