## Which of the 25 countries has sufficent data quaility and temporal coverage to remain in the running for thee modeling dataset

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
analysis_df = pd.read_csv("../data/processed/analysis_df.csv")

print(analysis_df.shape)
analysis_df.head()

(175, 17)

,AreaName,AreaCode,Year,Active mobile-broadband subscriptions,Estimated proportion of households with Internet access at home,Fixed-broadband subscriptions,Internet users (%),Percentage of the population covered by at least an LTE/WiMAX mobile network.,Population,Country Name,Country Code,Electricity_Access,Region,Income group,Mobile_Broadband_per_100,Fixed-broadband_per_100,Coverage_Use_Gap
0,Afghanistan,AFG,2018,6997208.0,7.270304,15999.0,16.799999,7.00,36743039.0,Afghanistan,AFG,93.4,"Middle East, North Africa, Afghanistan & Pakistan",Low income,19.043629,0.043543,-9.799999
1,Afghanistan,AFG,2019,7309797.0,8.438115,19683.0,17.600000,22.00,37856121.0,Afghanistan,AFG,97.7,"Middle East, North Africa, Afghanistan & Pakistan",Low income,19.309419,0.051994,4.400000
2,Afghanistan,AFG,2020,7422550.0,NaN,26570.0,17.048500,26.00,39068979.0,Afghanistan,AFG,97.7,"Middle East, North Africa, Afghanistan & Pakistan",Low income,18.998577,0.068008,8.951500
3,Afghanistan,AFG,2021,7422550.0,24.288903,26570.0,16.514299,26.00,40000412.0,Afghanistan,AFG,97.7,"Middle East, North Africa, Afghanistan & Pakistan",Low income,18.556184,0.066424,9.485701
4,Afghanistan,AFG,2022,22831896.0,27.592028,32313.0,15.866300,33.03,40578842.0,Afghanistan,AFG,85.3,"Middle East, North Africa, Afghanistan & Pakistan",Low income,56.265519,0.079630,17.163700

In [13]:
# Creating table to establish which countries have the most useful data for training the model

model_vars = [
    "Electricity_Access",
    "Internet users (%)",
    "Mobile_Broadband_per_100",
    "Fixed-broadband_per_100",
    "Percentage of the population covered by at least an LTE/WiMAX mobile network."
]

country_data_completeness = (
    analysis_df
    .groupby("Country Name")[model_vars]
    .agg(["count",( "missing", lambda x: x.isna().sum())])
)

country_data_completeness

                 Electricity_Access         Internet users (%)          \
                              count missing              count missing
Country Name
Afghanistan                       7       0                  7       0
Angola                            7       0                  7       0
Armenia                           7       0                  7       0
Barbados                          7       0                  7       0
Botswana                          7       0                  6       1
Burkina Faso                      7       0                  7       0
Cambodia                          7       0                  7       0
Colombia                          7       0                  7       0
Ethiopia                          7       0                  7       0
Honduras                          7       0                  7       0
India                             7       0                  7       0
Indonesia                         7       0                  7       0
Iraq                              7       0                  7       0
Israel                            7       0                  7       0
Jamaica                           7       0                  7       0
Japan                             7       0                  7       0
Kenya                             7       0                  7       0
Madagascar                        7       0                  7       0
Morocco                           7       0                  7       0
Papua New Guinea                  7       0                  7       0
Rwanda                            7       0                  7       0
Spain                             7       0                  7       0
Uganda                            7       0                  7       0
Ukraine                           7       0                  7       0
United States                     7       0                  7       0

                 Mobile_Broadband_per_100         Fixed-broadband_per_100  \
                                    count missing                   count
Country Name
Afghanistan                             7       0                       6
Angola                                  7       0                       7
Armenia                                 7       0                       7
Barbados                                6       1                       5
Botswana                                7       0                       7
Burkina Faso                            5       2                       7
Cambodia                                7       0                       7
Colombia                                7       0                       7
Ethiopia                                6       1                       6
Honduras                                7       0                       7
India                                   7       0                       7
Indonesia                               7       0                       7
Iraq                                    7       0                       7
Israel                                  7       0                       7
Jamaica                                 7       0                       7
Japan                                   6       1                       6
Kenya                                   7       0                       7
Madagascar                              7       0                       6
Morocco                                 7       0                       7
Papua New Guinea                        5       2                       6
Rwanda                                  7       0                       7
Spain                                   7       0                       7
Uganda                                  7       0                       6
Ukraine                                 7       0                       7
United States                           7       0                       7

                          \
                 missing
Country Name
Afghanistan            1
Angola                 0
Armenia                0
Barbados               2
Botswana               0
Burkina Faso           0
Cambodia               0
Colombia               0
Ethiopia               1
Honduras               0
India                  0
Indonesia              0
Iraq                   0
Israel                 0
Jamaica                0
Japan                  1
Kenya                  0
Madagascar             1
Morocco                0
Papua New Guinea       1
Rwanda                 0
Spain                  0
Uganda                 1
Ukraine                0
United States          0

                 Percentage of the population covered by at least an LTE/WiMAX mobile network.  \
                                                                                         count
Country Name
Afghanistan                                                       7
Angola                                                            7
Armenia                                                           7
Barbados                                                          6
Botswana                                                          7
Burkina Faso                                                      7
Cambodia                                                          7
Colombia                                                          7
Ethiopia                                                          6
Honduras                                                          7
India                                                             7
Indonesia                                                         7
Iraq                                                              7
Israel                                                            7
Jamaica                                                           7
Japan                                                             7
Kenya                                                             7
Madagascar                                                        7
Morocco                                                           7
Papua New Guinea                                                  6
Rwanda                                                            7
Spain                                                             7
Uganda                                                            6
Ukraine                                                           6
United States                                                     7


                 missing
Country Name
Afghanistan            0
Angola                 0
Armenia                0
Barbados               1
Botswana               0
Burkina Faso           0
Cambodia               0
Colombia               0
Ethiopia               1
Honduras               0
India                  0
Indonesia              0
Iraq                   0
Israel                 0
Jamaica                0
Japan                  0
Kenya                  0
Madagascar             0
Morocco                0
Papua New Guinea       1
Rwanda                 0
Spain                  0
Uganda                 1
Ukraine                1
United States          0

In [14]:
# Locating the missing values in data

missing_records = (
    analysis_df[analysis_df[model_vars].isna().any(axis=1)]
    [["Country Name", "Year"] + model_vars].sort_values(['Country Name', "Year"]) 
)

missing_records

,Country Name,Year,Electricity_Access,Internet users (%),Mobile_Broadband_per_100,Fixed-broadband_per_100,Percentage of the population covered by at least an LTE/WiMAX mobile network.
6,Afghanistan,2024,87.8,16.094999,60.099082,NaN,37.324101
26,Barbados,2023,100.0,69.675102,NaN,NaN,NaN
27,Barbados,2024,100.0,70.364700,59.936205,NaN,99.000000
33,Botswana,2023,76.0,NaN,111.872300,6.164958,91.000000
37,Burkina Faso,2020,18.5,12.973200,NaN,0.065083,26.920000
40,Burkina Faso,2023,21.7,25.361200,NaN,0.459463,42.390000
56,Ethiopia,2018,44.8,15.886200,NaN,NaN,NaN
111,Japan,2024,100.0,85.541531,NaN,NaN,98.100000
125,Madagascar,2024,42.5,18.677900,28.197129,NaN,34.626694
133,Papua New Guinea,2018,16.6,12.357900,NaN,NaN,NaN
138,Papua New Guinea,2023,20.5,18.561300,NaN,0.228112,70.000000
154,Uganda,2018,41.9,9.326300,34.549645,NaN,NaN
161,Ukraine,2018,100.0,62.553155,47.155521,12.803256,NaN